# Generated by Django 6.0.4 on 2026-04-29 15:04

import app_legallens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cliente', models.CharField(default='Desconocido', max_length=255)),
                ('tipo', models.CharField(choices=[('ALQUILER', 'Contrato de Alquiler'), ('NDA', 'Acuerdo de Confidencialidad (NDA)')], default='ALQUILER', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('resultado_ia', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(upload_to=app_legallens.models.ruta_pdf)),
                ('nombre_orig_pdf', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
